### Login
POST http://localhost:8080/login?email=yerkebayev@unist.ac.kr&password=123hey

### Register
POST http://localhost:8080/register
Content-Type: application/json

{
  "name": "Marat",
  "surname": "Yerkebayev",
  "email": "yerkebayev@unist.ac.kr",
  "password": "123hey",
  "role": 1
}

### Add preferred club types
POST http://localhost:8080/api/10/choose_types
Content-Type: application/json

[1, 5, 7]

### Get clubs by user prefer
GET http://localhost:8080/api/15/clubs/prefer

### Get clubs by type of that club
http://localhost:8080/api/1/clubs/1/prefer

### Get all clubs
GET http://localhost:8080/api/10/clubs

### Get first club
GET http://localhost:8080/api/1/clubs/1

### Get average rating of club
GET http://localhost:8080/api/5/clubs/14/ratings/avg

### Get all ratings and comments of club
GET http://localhost:8080/api/5/clubs/14/ratings

### Add rating in club
POST http://localhost:8080/api/1/clubs/1/ratings
Content-Type: application/json

{
    "rating": 5,
    "comment": "This club is great!"
}

### Edit rating
PUT http://localhost:8080/api/1/clubs/1/ratings/539
Content-Type: application/json

{
  "rating": 7,
  "comment": "This club is amazing!"
}

### Delete rating
DELETE http://localhost:8080/api/1/clubs/1/ratings/539


### Login
POST http://localhost:8080/admin/login?email=a210107096@unist.ac.kr&password=123abc

### Get all clubs for admin
GET http://localhost:8080/admin/clubs
Accept: application/json

### Add club
POST http://localhost:8080/admin/clubs
Content-Type: application/json

{
  "name": "Marat",
  "email": "marat@gmail.com",
  "clubType_id": 2,
  "description": "Marat Yerkebayev is the best!",
  "mission": "Bar",
  "contact": "87009809778",
  "head_id": 2
}

### Edit club
PUT http://localhost:8080/admin/clubs/5
Content-Type: application/json

{
  "name": "Marat Demo",
  "email": "marat@gmail.com",
  "clubType_id": 3,
  "description": "Marat Yerkebayev is the best!",
  "mission": "Bar",
  "contact": "87009809778",
  "head_id": 2
}

### Delete club
DELETE http://localhost:8080/admin/clubs/3
