### Login
POST http://localhost:8080/api/login?email=ab@my.com&password=123

### Register
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "Abe",
  "surname": "Bee",
  "email": "ab@my.com",
  "password": "123",
  "role": 1
}

### Add preferred club types
POST http://localhost:8080/api/1/choose_types
Content-Type: application/json

[1, 2, 3]


### Get all clubs
GET http://localhost:8080/api/clubs

### Get first club
GET http://localhost:8080/api/clubs/1

### Add rating in club
POST http://localhost:8080/api/clubs/1/ratings
Content-Type: application/json

{
    "rating": 5,
    "comment": "This club is great!",
    "user_id": 1
}

### Edit rating
PUT http://localhost:8080/api/clubs/1/ratings/8
Content-Type: application/json

{
  "rating": 7,
  "comment": "This club is amazing!"
}

### Delete rating
DELETE http://localhost:8080/api/clubs/1/ratings/8