name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: 18
          distribution: adopt

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Run tests with Maven
        run: mvn test --no-transfer-progress
